[package]
name = "kitty-lang-ast"
version = "0.0.0"
authors = ["Scott MacDonald"]
description = "The abstract syntax tree and supporting utils for the kitty language"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true